'use client'
import Image from 'next/image';
import { ParticlesComponent } from '../src/particles/index'
import Footer from '../src/footer/index'

import logo from "../public/logo.png"

export const metadata = {
  title: 'Łukasz Kurczab - Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{background: "radial-gradient(circle at 35% 15%, #444, #222 40%)"}}>
        <ParticlesComponent />
        <Image src={logo} alt="" className="layout__logo" />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
